# Check out https://pre-commit.com/ for documentation
# and https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.16.0
# Don't set language_version -- it's only useful if we have multiple
# python versions or our build uses a different env than runtime
repos:
  # --- Meta hooks ---
  #- hooks:
  # This one is useful, but it will fail if, e.g., you don't have a single yaml file
  #  - id: check-hooks-apply
  # This one will fail, e.g., if you don't have a recipes/ file, which is excluded here
  #   - id: check-useless-excludes
  #  repo: meta

  # --- Built-in hooks --
  - hooks:
      - id: check-symlinks
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
        exclude: "^tests/resources/"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      # This one is slow and doesn't check for much
      # - detect-private-key
      # This is very slow, so I recommend disabling it.
      #- id: check-added-large-files
      # The Conda recipe meta.yaml files are actually templates, not valid YAML
      - id: check-yaml
        exclude: ^recipes/.*
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages: ["commit-msg"]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3

  # --- Strip output from .ipynb files ---
  # - hooks:
  #     - id: nbstripout
  #       files: ".ipynb"
  #   repo: https://github.com/kynan/nbstripout
  #   rev: 0.5.0

  # --- Linters ---
  - hooks:
      - id: dockerfile_lint
    repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  # make sure to run black *after* isort
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 21.12b0
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
  # run black on Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.3
    hooks:
      - id: nbqa-black
  - repo: https://github.com/pre-commit/mirrors-prettier
    hooks:
      - id: prettier
        stages: [commit]
        exclude: ^recipes/.*
    rev: v2.4.1
