name: Build on push
on:
  - push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile exmaple document
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: example
          root_file: MAIN.tex
          latexmk_use_lualatex: true
          extra_system_packages: |
            py-pygments
          extra_fonts: |  # TODO
        env:
          TEXINPUTS: '../src//:'
